version: "3.0"
services:
  marketing_server:
    build: .
    image: rafipayment_marketing_server
    container_name: marketing_server
    environment:
      - NODE_ENV=staging
      - FORCE_COLOR=1
    ports:
      - 3001:3001
    deploy:
      restart_policy:
        condition: any

networks:
  default:
    external:
      name: rafipayment_network

